### ISSUE TITLE
Getting started trouble

### ISSUE THREAD

**Issue by intoro** [scherroman/mugen#17]
I ran these commands to get started, but when I try anything mugen wants a missing 'bin' directory. Any ideas?

mkdir 3_try
cd 3_try
git clone https://github.com/scherroman/mugen.git
cd mugen
conda env create -f environment.yml
  everything downloads...
source activate mugen
cd src/bin/
python cli.py --help  
     Recieve this error:
Traceback (most recent call last):
File "cli.py", line 9, in <module>
  import bin.constants as cli_c
ModuleNotFoundError: No module named 'bin'

**Comment by scherroman** [comment]
Hey intoro,

This is an oversight on my part caused by not having mugen install as a proper package. 

To fix this you should add the mugen package directory to your PYTHONPATH environment variable, so that python can find it.
```
export PYTHONPATH=$PYTHONPATH:PATH_TO_MUGEN_REPO/src
```

Depending on where you've installed the mugen repo on your computer, `PATH_TO_MUGEN_REPO` will look something like `/Users/jeremy/Documents/github_repos/mugen`
